Add test coverage standard
canonical/is-charms-contributing-guide pull request #9
Opened 2022-08-26 05:18 UTC by jdkandersson

Closes #6

2022-08-26 07:56 UTC, arturo-seijas requested changes
Just a minor thing

2022-08-26 07:56 UTC, arturo-seijas commented on CONTRIBUTING.md
> +Unit tests check whether the intended fucntionality has been implemented. This
You have a typo in here: fucntionality

2022-08-26 11:01 UTC, jdkandersson commented on CONTRIBUTING.md
> +Unit tests check whether the intended fucntionality has been implemented. This
Thank you, fixed this one and another one

2022-08-26 11:12 UTC, arturo-seijas approved these changes
LGTM

2022-08-29 16:21 UTC, mthaddon commented on CONTRIBUTING.md
> +This ensures a high coverage minimum and no coverage regression.
Should we talk about the mechanism that we plan to use for this, i.e. in Indico currently we have this in the `tox.ini`:

```
[testenv:unit]
description = Run unit tests
deps =
    pytest
    coverage[toml]
    -r{toxinidir}/requirements.txt
commands =
    coverage run --source={[vars]src_path} \
        -m pytest --ignore={[vars]tst_path}integration -v --tb native -s {posargs}
    coverage report --fail-under=90
```

2022-08-30 01:57 UTC, jdkandersson commented on CONTRIBUTING.md
> +This ensures a high coverage minimum and no coverage regression.
Yes, there is a setting in `[tool.coverage.report]` for `pyproject.toml` called `fail_under`, I'll propose we use that to keep configuration in one place

2022-08-30 07:04 UTC, mthaddon approved these changes
LGTM, thx!

2022-08-31 01:30 UTC, merged